name: Error Tracker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Google test submodule checkout
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: CMake setup
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure build
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests on the correct implementation
        run: ./build/test_multiplication_correct

      - name: Run tests
        run: ./error_tracker.sh ./build/test_multiplication_incorrect > errors.txt

      - name: Commit the found errors in the repository
        run: |
          git config --global user.name 'FattiMei'
          git config --global user.email 'FattiMei@users.noreply.github.com'
          git add errors.txt
          git commit -m "Automated error filtering"
          git push

