name: Error Tracker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google test submodule checkout
        uses: textbook/git-checkout-submodule-action@master

      - name: CMake setup
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure build
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ./build/test_multiplication
