name: Error Tracker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Google test submodule checkout
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: CMake setup
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure build
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          ./build/test_multiplication &> tmp || true
          grep "^Error:*" tmp | awk '{print $2, $i}' | sort -n | uniq | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}' > errors.txt
          rm tmp

      - name: Upload found errors
        uses: actions/upload-artifact@v4
        with:
          name: found_errors
          path: errors.txt

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

